### ISSUE TITLE
check in fail in v2.1

### ISSUE THREAD

**Issue by nauyisu022** [RyaoChengfeng/wzj-checkin#1]
check in fail in v2.1
 util/cron.go:34 check in fail, error: Get "https://v18.teachermate.cn/wechat/wechat/guide/signin?openid=xxxx": EOF
 util/cron.go:34 check in fail, error: request wrong

**Comment by RyaoChengfeng** [comment]
The API is no longer available. I don't have time to maintain this project. 
Additionally, I have not been able to find a suitable alternative.

**Comment by RyaoChengfeng** [comment]
fixed
